version: '3.7'

services:

  database:
    restart: always
    image: postgres:12
    env_file:
      - ./config/postgres/env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

  shotener_ms:
    restart: always
    build: ./url_shortener_service
    volumes:
      - ./url_shortener_service:/shortener_ms
    networks:
      - nginx_network

  messenger:
    restart: always
    build: .
    volumes: 
      - ./messenger:/messenger
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    restart: always
    image: openresty/openresty:alpine
    ports:
      - 8000:443
      - 443:443
      - 7000:7000
    volumes:
      - ./config/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./config/certs/dev.crt:/messenger/dev.crt
      - ./config/certs/dev.key:/messenger/dev.key
    depends_on:
      - messenger
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
    driver: local
  static_volume:
    driver: local
